version: '3.9'

services:
  booking-core-notification_app-service:
    container_name: 'booking-core-notification_app-service'
    build: .
    ports:
      - 8083:8083
    networks:
      - booking-core
    depends_on:
      - booking-core-notification_mongo-db
#    environment:
#      DATABASE_URL: booking-core-notification_mongo-db

  booking-core-notification_mongo-db:
    container_name: 'booking-core-notification_mongo-db'
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    volumes:
      - data:/data
    networks:
      - booking-core
volumes:
  data: { }
networks:
  booking-core:
    name: booking-core
    driver: bridge