server:
  port: 8081
spring:
  application:
    name: booking-core-notification
  kafka:
    bootstrap-servers: localhost:9092
  data:
    mongodb:
      #      authentication-database: admin
      #      username: admin
      #      password: admin
      database: core
      port: 27017
      host: localhost
