server:
  port: 8081
spring:
  application:
    name: booking-core-notification
  kafka:
#    bootstrap-servers: localhost:9092
    bootstrap-servers: booking-core_kafka:9092
  data:
    mongodb:
      #      authentication-database: admin
      #      username: admin
      #      password: admin
      database: core
      port: 27017
#      host: localhost
      host: booking-core-notification_mongo-db
